package com.org.bgv.enums;

public enum ActivityType {

    CASE_CREATED,

    CHECK_STARTED,

    ACTION_CREATED,

    METHOD_EXECUTED,

    COMMUNICATION_SENT,

    RESPONSE_RECEIVED,

    EVIDENCE_UPLOADED,

    STATUS_CHANGED,

    SLA_TRIGGERED,

    VERIFICATION_COMPLETED,
    CASE_ASSIGNED,
    CASE_STATUS_CHANGED,

    CHECK_CREATED,
    CHECK_STATUS_CHANGED,

    EXECUTION_STARTED,
    EXECUTION_COMPLETED,

    METHOD_SELECTED,
    METHOD_COMPLETED,

    EVIDENCE_DELETED,

    NOTE_ADDED,
    REMARK_UPDATED,
    DOCUMENT_UPLOADED,
    DOCUMENT_DELETED,
    FIELD_AGENT_ASSIGNED,
    FIELD_AGENT_REASSIGNED,
    
    MARK_VERIFIED,
    CASE_COMPLETED,
    REPORT_SHARED,
    MARK_DISCREPANCY_FOUND,
    ADDRESS_NOT_FOUND,
    CANDIDATE_NOT_AVAILABLE,
    MARK_UNABLE_TO_VERIFY,
    DOCUMENT_UPLOAD_FAILED,

}
