package com.org.bgv.enums;

public enum VerificationExecutionAction {

	UPLOAD_EVIDENCE,
    SEND_REMINDER,
    MARK_RESPONSE_RECEIVED,

    MARK_UNDER_REVIEW,
    COMPLETE,

    ADD_NOTE,
    CONTACT_CANDIDATE,

    CANCEL,
    MAKE_PHONE_CALL,
    MARK_PHONE_CALL_COMPLETED,
    
    
    MARK_VERIFIED,
    MARK_DISCREPANCY_FOUND,
    MARK_UNABLE_TO_VERIFY,
    ASSIGN_FIELD_AGENT,
    SCHEDULE_VISIT,
    CHANGE_FIELD_AGENT,
    START_VISIT,
    RESCHEDULE_VISIT,
    MARK_VISIT_COMPLETED,
    MARK_ADDRESS_NOT_FOUND,
    MARK_CANDIDATE_NOT_AVAILABLE,
    CAPTURE_LOCATION,
    APPROVE,
    REWORK,
    ESCALATE,
    UNDER_REVIEW,
    SEND_EMAIL,
    RESEND_EMAIL,
    MARK_EMAIL_VERIFICATION_COMPLETED
    
}
